trigger:
  branches:
    include:
    - main
  paths:
    include:
      - 'ProductApp/*'
      - 'ProductApp.Models/*'
pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  working-dir: 'ProductApp'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core 6'
  inputs:
    version: 6.x
 
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: 'ProductApp/*.csproj'
    feedsToUse: 'select'
 
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'ProductApp/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'ProductApp/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    ArtifactName: productapp

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure för studenter(21ec1d79-0537-4fec-8e24-5abce860535e)'
    appType: 'webApp'
    WebAppName: 'AA-ProductApp'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/ProductApp.zip'